services:
  splunk:
    image: splunk/splunk:9.3.1
    container_name: splunk
    environment:
      - SPLUNK_PASSWORD=adminadmin1
      - SPLUNK_START_ARGS=--accept-license
    ports:
      - 8000:8000   # Splunk Web (HTTPS)
      - 8088:8088   # HTTP Event Collector
      - 9997:9997   # Universal Forwarder
      - 8089:8089   # Management Port for REST API access
    volumes:
      - ./splunk/default.yml:/tmp/defaults/default.yml
      - ./splunk/mockdata.csv:/data/mockdata.csv
      - ./splunk/certificates:/opt/splunk/etc/auth/mycerts  # Mounting SSL certificates
    networks:
      - splunk_network

networks:
  splunk_network:
    driver: bridge
    attachable: true
